// Catalog of AI-powered audits. Each audit tells the client which local-storage
// datasets to snapshot before calling the server function. `dataKeys` are the
// keys used by localCrud (they are stored as `dms:<key>`).

export type AuditCategory =
  | "hr"
  | "finance"
  | "operations"
  | "commercial"
  | "governance"
  | "it"
  | "overall";

export type AuditDef = {
  id: string;
  title: string;
  category: AuditCategory;
  description: string;
  icon: string; // lucide icon key handled by the audit page
  dataKeys: string[]; // localStorage dataset keys to snapshot
  focus: string[]; // hints the AI uses to guide the audit
};

export const AUDIT_CATEGORY_LABEL: Record<AuditCategory, string> = {
  hr: "HR & People",
  finance: "Finance & Compliance",
  operations: "Operations & Delivery",
  commercial: "Commercial & Sales",
  governance: "Governance & Legal",
  it: "IT & Security",
  overall: "Organization-wide",
};

export const AUDITS: AuditDef[] = [
  // HR & People
  {
    id: "hr-compliance",
    title: "HR Compliance Audit",
    category: "hr",
    description: "Reviews employee records, EOBI/PESSI, contracts and statutory HR compliance.",
    icon: "UserCog",
    dataKeys: ["employees", "hr"],
    focus: ["Missing CNIC / NTN / EOBI", "Contract expiry", "Salary structure", "Statutory deductions"],
  },
  {
    id: "payroll-accuracy",
    title: "Payroll Accuracy Audit",
    category: "hr",
    description: "Checks payroll calculations, tax slabs, allowances and net-pay consistency.",
    icon: "Wallet",
    dataKeys: ["hr", "employees"],
    focus: ["Gross vs Net", "Income tax slabs", "EOBI @ 1%", "Overtime & bonuses"],
  },
  {
    id: "attendance-leave",
    title: "Attendance & Leave Audit",
    category: "hr",
    description: "Detects excessive lates, absentees, unbalanced leaves and shift issues.",
    icon: "Clock",
    dataKeys: ["attendance_v2", "employees"],
    focus: ["Late arrivals", "Absentee ratio", "Overtime abuse", "Leave balances"],
  },
  {
    id: "employee-data",
    title: "Employee Data Completeness",
    category: "hr",
    description: "Highlights missing profile fields, bank accounts, next of kin and documents.",
    icon: "Users",
    dataKeys: ["employees"],
    focus: ["CNIC", "Bank details", "Emergency contact", "Job title"],
  },

  // Finance & Compliance
  {
    id: "invoice-receivables",
    title: "Invoice & Receivables Audit",
    category: "finance",
    description: "Aging analysis of unpaid invoices, DSO, top defaulters and dispute risks.",
    icon: "Receipt",
    dataKeys: ["invoices", "clients_v2"],
    focus: ["Overdue > 30/60/90 days", "Top defaulters", "DSO", "Bad debt provision"],
  },
  {
    id: "financial-health",
    title: "Financial Health Audit",
    category: "finance",
    description: "Overall P&L, cash position, expense ratios, revenue trend and burn.",
    icon: "TrendingUp",
    dataKeys: ["finance_v2", "finance_accounts_v1", "invoices"],
    focus: ["Revenue vs expenses", "Cash runway", "Category concentration"],
  },
  {
    id: "cashflow",
    title: "Cash Flow Audit",
    category: "finance",
    description: "Inflows vs outflows by month, account balances and liquidity risks.",
    icon: "Coins",
    dataKeys: ["finance_v2", "finance_accounts_v1"],
    focus: ["Monthly inflow/outflow", "Bank vs cash mix", "Liquidity"],
  },
  {
    id: "tax-compliance",
    title: "Tax & Statutory Compliance",
    category: "finance",
    description: "GST/withholding, invoice tax coverage, missing tax ids and FBR readiness.",
    icon: "Percent",
    dataKeys: ["invoices", "clients_v2", "docs"],
    focus: ["Sales tax on invoices", "Withholding", "NTN/STRN on clients", "Filing dates"],
  },
  {
    id: "expense",
    title: "Expense & Vendor Audit",
    category: "finance",
    description: "Expense categorisation, unusual spikes, duplicate payments and vendor spread.",
    icon: "ShoppingBag",
    dataKeys: ["finance_v2"],
    focus: ["Category concentration", "Duplicate refs", "Unusual spikes"],
  },
  {
    id: "quotation-conversion",
    title: "Quotation Conversion Audit",
    category: "commercial",
    description: "Quote→invoice conversion rate, expired quotations and pricing consistency.",
    icon: "FileSpreadsheet",
    dataKeys: ["quotations", "invoices", "clients_v2"],
    focus: ["Win rate", "Aging pending quotes", "Average deal value"],
  },

  // Commercial & Sales
  {
    id: "crm-health",
    title: "Clients & CRM Health",
    category: "commercial",
    description: "Client status distribution, dormant accounts and CRM data quality.",
    icon: "UserRoundCog",
    dataKeys: ["clients_v2", "invoices"],
    focus: ["Active vs dormant", "Missing contact info", "Revenue concentration"],
  },
  {
    id: "sales-pipeline",
    title: "Sales Pipeline Audit",
    category: "commercial",
    description: "Deals by stage, stuck opportunities, forecast accuracy and win/loss.",
    icon: "TrendingUp",
    dataKeys: ["clients_v2", "quotations", "invoices"],
    focus: ["Stage bottlenecks", "Stale deals", "Forecast vs actual"],
  },
  {
    id: "feedback-quality",
    title: "Customer Feedback Audit",
    category: "commercial",
    description: "Reviews CSAT/NPS trends, complaint themes and unresolved feedback.",
    icon: "PhoneCall",
    dataKeys: ["feedback_calls", "clients_v2"],
    focus: ["Average rating", "Negative themes", "Follow-up gaps"],
  },

  // Operations & Delivery
  {
    id: "project-delivery",
    title: "Project Delivery Audit",
    category: "operations",
    description: "Project status, deadline slippage, budget health and delivery risks.",
    icon: "FolderKanban",
    dataKeys: ["pm_projects", "pm_tasks", "clients_v2"],
    focus: ["On-time delivery", "Budget vs actual", "Blocked projects"],
  },
  {
    id: "task-backlog",
    title: "Task Backlog Audit",
    category: "operations",
    description: "Backlog age, overdue tasks, workload distribution and unassigned items.",
    icon: "CheckSquare",
    dataKeys: ["tasks", "pm_tasks", "employees"],
    focus: ["Overdue tasks", "Unassigned", "Workload per person"],
  },
  {
    id: "support-sla",
    title: "Support SLA Audit",
    category: "operations",
    description: "Ticket response/resolution times, breached SLAs and recurring issues.",
    icon: "LifeBuoy",
    dataKeys: ["support_v2", "clients_v2"],
    focus: ["First response", "Resolution time", "SLA breaches", "Repeat clients"],
  },
  {
    id: "asset-inventory",
    title: "Assets & Inventory Audit",
    category: "operations",
    description: "Asset assignments, warranty coverage, missing items and stock levels.",
    icon: "Package",
    dataKeys: ["inventory", "inventory_consumables", "inventory_assignments", "inventory_maintenance"],
    focus: ["Unassigned assets", "Expired warranty", "Low stock", "Maintenance overdue"],
  },
  {
    id: "asset-depreciation",
    title: "Fixed Asset Depreciation",
    category: "operations",
    description: "Age of assets, depreciation status, disposal candidates and book value.",
    icon: "Boxes",
    dataKeys: ["inventory"],
    focus: ["Age > 4 years", "Depreciated to zero", "Disposal candidates"],
  },

  // Governance & Legal
  {
    id: "document-expiry",
    title: "Document & Contract Expiry",
    category: "governance",
    description: "Expired or expiring contracts, missing renewals and confidentiality mix.",
    icon: "FileText",
    dataKeys: ["docs", "generated_docs"],
    focus: ["Expired", "Expiring in 30/60 days", "Missing owner"],
  },
  {
    id: "case-status",
    title: "Legal Case Status Audit",
    category: "governance",
    description: "Open cases, upcoming hearings, exposure and internal disciplinary flow.",
    icon: "Scale",
    dataKeys: ["cases_v2"],
    focus: ["Upcoming hearings", "Open exposure", "Internal disciplinary"],
  },
  {
    id: "notice-log",
    title: "Communication & Notices Audit",
    category: "governance",
    description: "Notice frequency, unacknowledged notices and communication gaps.",
    icon: "Bell",
    dataKeys: ["notices_v1"],
    focus: ["Unacknowledged", "Broadcast history", "Compliance notices"],
  },

  // IT & Security
  {
    id: "it-security",
    title: "IT Security & Credentials",
    category: "it",
    description: "Password hygiene, credential rotation, subscription risks and access.",
    icon: "ShieldCheck",
    dataKeys: ["it_credentials", "it_subscriptions", "it_domains", "it_servers"],
    focus: ["Weak passwords", "Rotation overdue", "Auto-renewals", "Expired SSL"],
  },
  {
    id: "access-control",
    title: "Access Control Audit",
    category: "it",
    description: "User roles, dormant accounts, privileged access and login anomalies.",
    icon: "Lock",
    dataKeys: ["users_v1", "user_sessions"],
    focus: ["Admin count", "Dormant users", "Suspicious logins"],
  },

  // New modules — Interns, Catalog, Transactions
  {
    id: "interns-program",
    title: "Interns Program Audit",
    category: "hr",
    description: "Reviews internship program: active vs completed interns, stipends, supervisor coverage, terminations and certificate issuance.",
    icon: "GraduationCap",
    dataKeys: ["devionic.interns.v1", "employees"],
    focus: ["Active interns", "Terminated / dropout ratio", "Certificate issued", "Missing supervisor", "Stipend spend"],
  },
  {
    id: "catalog-pricing",
    title: "Products & Services Catalog Audit",
    category: "commercial",
    description: "Reviews product & service catalog: SKU coverage, pricing consistency, inactive items and margin outliers.",
    icon: "Package",
    dataKeys: ["catalog", "invoices", "quotations"],
    focus: ["SKU / code coverage", "Missing price", "Inactive items", "Most / least sold"],
  },
  {
    id: "transactions-collections",
    title: "Transactions & Collections Audit",
    category: "finance",
    description: "Reviews all invoice payments — full / partial / due, collection method mix, and posting to accounts.",
    icon: "Receipt",
    dataKeys: ["payments", "invoices", "finance_v2", "finance_accounts_v1"],
    focus: ["Full vs partial paid", "Due invoices aging", "Cash vs bank vs wallet mix", "Untracked receipts"],
  },
  {
    id: "login-logs",
    title: "Login Logs Audit",
    category: "it",
    description: "Reviews user login history, IP/device anomalies, failed attempts and off-hours access.",
    icon: "LogIn",
    dataKeys: ["sb:user_login_logs", "sb:app_users", "users_v1"],
    focus: ["Failed logins", "Unusual IP / device", "Off-hours logins", "Concurrent sessions"],
  },
  {
    id: "activity-logs",
    title: "Activity Logs Audit",
    category: "it",
    description: "Analyzes user activity trails, sensitive actions, deletions and audit-trail gaps.",
    icon: "Activity",
    dataKeys: ["sb:user_activity_logs", "sb:app_users", "users_v1"],
    focus: ["Delete / update spikes", "Privileged actions", "Idle users", "Coverage gaps"],
  },
  {

    id: "otp-security",
    title: "OTP & IP Verification Audit",
    category: "it",
    description: "Reviews OTP issuance, verification success/failure, and new-IP challenges.",
    icon: "ShieldAlert",
    dataKeys: ["sb:otp_logs", "sb:user_login_logs", "sb:app_users"],
    focus: ["OTP failure rate", "Expired codes", "New-IP anomalies", "Brute-force patterns"],
  },
  {
    id: "email-delivery",
    title: "Email Delivery Audit",
    category: "it",
    description: "Analyzes outbound email delivery, provider errors and category coverage.",
    icon: "Mail",
    dataKeys: ["sb:email_logs"],
    focus: ["Failure rate", "Provider errors", "Bounces", "Category volume"],
  },
  {
    id: "system-events",
    title: "System Events Audit",
    category: "it",
    description: "Reviews system-level events, errors and warnings across the platform.",
    icon: "Server",
    dataKeys: ["sb:system_logs"],
    focus: ["Error spikes", "Repeated warnings", "Source hotspots", "Silent modules"],
  },



  // Extended audits (added set — brings total to 40+)
  {
    id: "recruitment-pipeline",
    title: "Recruitment Pipeline Audit",
    category: "hr",
    description: "Reviews hiring funnel, time-to-hire, open positions and candidate flow quality.",
    icon: "Users",
    dataKeys: ["employees", "devionic.interns.v1"],
    focus: ["Open positions", "Time-to-hire", "Source mix", "Conversion"],
  },
  {
    id: "training-development",
    title: "Training & Development Audit",
    category: "hr",
    description: "Coverage of trainings, certifications issued, skill gaps and development spend.",
    icon: "GraduationCap",
    dataKeys: ["employees", "generated_docs"],
    focus: ["Certificates issued", "Skill coverage", "Training frequency"],
  },
  {
    id: "diversity-inclusion",
    title: "Diversity & Inclusion Audit",
    category: "hr",
    description: "Gender / role / department diversity ratios and inclusion indicators.",
    icon: "Users",
    dataKeys: ["employees"],
    focus: ["Gender mix", "Dept distribution", "Leadership ratio"],
  },
  {
    id: "payables-aging",
    title: "Payables & Vendor Aging",
    category: "finance",
    description: "Vendor payables, aging buckets, top vendors owed and overdue liabilities.",
    icon: "Wallet",
    dataKeys: ["purchase_orders_v1", "vendors_v1", "finance_v2"],
    focus: ["Overdue payables", "Top vendors", "Aging 30/60/90"],
  },
  {
    id: "procurement-efficiency",
    title: "Procurement Efficiency Audit",
    category: "finance",
    description: "PO cycle time, GRN gaps, vendor concentration and procurement leakages.",
    icon: "ShoppingBag",
    dataKeys: ["purchase_orders_v1", "vendors_v1", "inventory"],
    focus: ["PO cycle time", "GRN pending", "Vendor concentration"],
  },
  {
    id: "budget-variance",
    title: "Budget vs Actual Variance",
    category: "finance",
    description: "Variance analysis of planned vs actual spend across categories & projects.",
    icon: "TrendingUp",
    dataKeys: ["finance_v2", "pm_projects"],
    focus: ["Category variance", "Project overrun", "Forecast accuracy"],
  },
  {
    id: "customer-retention",
    title: "Customer Retention Audit",
    category: "commercial",
    description: "Repeat business ratio, churn signals, LTV concentration and win-back candidates.",
    icon: "UserRoundCog",
    dataKeys: ["clients_v2", "invoices", "feedback_calls"],
    focus: ["Repeat clients", "Churn risk", "Top 20% revenue", "Dormant"],
  },
  {
    id: "pricing-margin",
    title: "Pricing & Margin Audit",
    category: "commercial",
    description: "Item-level margin, discount abuse, loss-leaders and pricing outliers.",
    icon: "Percent",
    dataKeys: ["catalog", "invoices", "quotations"],
    focus: ["Gross margin", "Discount usage", "Below-cost sales"],
  },
  {
    id: "inventory-turnover",
    title: "Inventory Turnover Audit",
    category: "operations",
    description: "Stock movement velocity, dead stock, reorder gaps and consumable burn.",
    icon: "Package",
    dataKeys: ["inventory", "inventory_consumables", "inventory_assignments"],
    focus: ["Turnover ratio", "Dead stock", "Reorder points", "Burn rate"],
  },
  {
    id: "meeting-productivity",
    title: "Meetings & Communication Audit",
    category: "operations",
    description: "Meeting cadence, notice traffic, chat volume and communication overhead.",
    icon: "PhoneCall",
    dataKeys: ["notices_v1", "feedback_calls"],
    focus: ["Meeting frequency", "Notice cadence", "Response gaps"],
  },
  {
    id: "risk-management",
    title: "Enterprise Risk Register",
    category: "governance",
    description: "Aggregates open cases, expiring docs, security gaps and financial exposure into a risk register.",
    icon: "ShieldAlert",
    dataKeys: ["cases_v2", "docs", "it_credentials", "invoices", "finance_v2"],
    focus: ["Top enterprise risks", "Impact vs likelihood", "Mitigation gaps"],
  },
  {
    id: "business-continuity",
    title: "Business Continuity Audit",
    category: "governance",
    description: "Backup posture, key-person dependencies, single points of failure and recovery readiness.",
    icon: "ShieldCheck",
    dataKeys: ["it_servers", "it_domains", "employees", "docs"],
    focus: ["Backup posture", "Key-person risk", "SPOF", "Recovery plan"],
  },
  {
    id: "data-privacy",
    title: "Data Privacy & PII Audit",
    category: "governance",
    description: "PII exposure across records, retention posture and consent hygiene.",
    icon: "Lock",
    dataKeys: ["employees", "clients_v2", "docs", "sb:app_users"],
    focus: ["PII fields", "Retention", "Consent trail"],
  },
  {
    id: "backup-recovery",
    title: "Backup & Recovery Audit",
    category: "it",
    description: "Backup frequency, restore tests, off-site copies and RPO/RTO posture.",
    icon: "Server",
    dataKeys: ["it_servers", "it_subscriptions"],
    focus: ["Backup frequency", "Restore test", "RPO/RTO"],
  },
  {
    id: "subscription-spend",
    title: "SaaS Subscription Audit",
    category: "it",
    description: "SaaS spend, overlapping tools, unused licenses and auto-renewal risks.",
    icon: "ShoppingBag",
    dataKeys: ["it_subscriptions"],
    focus: ["Total spend", "Overlap", "Unused seats", "Renewals"],
  },
  {
    id: "domain-ssl",
    title: "Domain & SSL Audit",
    category: "it",
    description: "Domain expiry, SSL validity, DNS hygiene and registrar concentration.",
    icon: "Lock",
    dataKeys: ["it_domains"],
    focus: ["Domain expiry", "SSL expiry", "Registrar risk"],
  },

  // Overall
  {
    id: "org-health",
    title: "Organization Health Audit",
    category: "overall",
    description: "Cross-module health score covering people, money, delivery and risk.",
    icon: "Sparkles",
    dataKeys: [
      "employees", "hr", "clients_v2", "invoices", "quotations",
      "pm_projects", "pm_tasks", "tasks", "support_v2",
      "inventory", "docs", "cases_v2", "finance_v2", "finance_accounts_v1",
    ],
    focus: ["Overall score", "Top 5 risks", "Top 5 opportunities"],
  },
  {
    id: "complete-detailed",
    title: "Complete Detailed Audit",
    category: "overall",
    description: "Full 360° organizational audit — every module, logs, finance, delivery, governance and security in one deep report.",
    icon: "Layers",
    dataKeys: [
      "employees", "hr", "attendance_v2",
      "clients_v2", "quotations", "invoices", "payments",
      "pm_projects", "pm_tasks", "tasks",
      "support_v2", "feedback_calls",
      "inventory", "inventory_consumables", "inventory_assignments", "inventory_maintenance",
      "docs", "generated_docs", "cases_v2", "notices_v1",
      "finance_v2", "finance_accounts_v1",
      "it_credentials", "it_subscriptions", "it_domains", "it_servers",
      "users_v1", "user_sessions",
      "devionic.interns.v1", "catalog",
      "sb:user_login_logs", "sb:user_activity_logs", "sb:app_users",
      "sb:otp_logs", "sb:email_logs", "sb:system_logs",

    ],
    focus: [
      "Executive 360 overview", "Cross-module risks", "Compliance posture",
      "Financial health", "Delivery health", "People & HR",
      "Security & access", "Top 10 prioritized actions",
    ],
  },
];
