// Registry of documents generated by the system (e.g. Document Center letters).
// Persists in browser localStorage so they surface in the Docs & Records module.
import type { LetterhaedPdfOptions } from "@/lib/letterhead-pdf";

export type GeneratedDocCategory = "hr_letter" | "contract" | "notification" | "report" | "other";

export type GeneratedDoc = {
  id: string;                 // unique — "gen-<timestamp>-<rand>"
  doc_no: string;             // Reference number
  title: string;              // Subject / template name
  template_id: string;
  template_name: string;
  category: GeneratedDocCategory;
  party?: string;             // recipient (first line)
  owner: string;              // signatory name
  signatory_title?: string;
  date: string;               // dd/mm/yyyy
  created_at: string;         // ISO
  opts: LetterhaedPdfOptions; // full options to allow re-generation
  source: "letters";
};

const KEY = "dms:generated_docs";

function safeParse(): GeneratedDoc[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(KEY);
    if (!raw) return [];
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? arr : [];
  } catch { return []; }
}

function save(rows: GeneratedDoc[]) {
  window.localStorage.setItem(KEY, JSON.stringify(rows));
  try {
    window.dispatchEvent(new CustomEvent("dms:generated_docs:changed"));
  } catch { /* noop */ }
}

export const generatedDocs = {
  list(): GeneratedDoc[] {
    return safeParse().sort((a, b) => (b.created_at > a.created_at ? 1 : -1));
  },
  add(entry: Omit<GeneratedDoc, "id" | "created_at" | "source"> & { source?: "letters" }): GeneratedDoc {
    const rows = safeParse();
    // Deduplicate by doc_no + template_id — regeneration replaces the previous entry.
    const filtered = rows.filter((r) => !(r.doc_no === entry.doc_no && r.template_id === entry.template_id));
    const row: GeneratedDoc = {
      ...entry,
      source: entry.source ?? "letters",
      id: `gen-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      created_at: new Date().toISOString(),
    };
    save([row, ...filtered]);
    return row;
  },
  remove(id: string) {
    save(safeParse().filter((r) => r.id !== id));
  },
  clear() { save([]); },
};

export function categoryFromTemplate(c: "hr" | "client" | "notification"): GeneratedDocCategory {
  if (c === "hr") return "hr_letter";
  if (c === "client") return "contract";
  return "notification";
}
