/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalAdminRouteImport } from './routes/portal-admin'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as ItRouteImport } from './routes/it'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InternsRouteImport } from './routes/interns'
import { Route as HrRouteImport } from './routes/hr'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EmployeesHistoryRouteImport } from './routes/employees-history'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClientsHistoryRouteImport } from './routes/clients-history'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalTicketsRouteImport } from './routes/portal.tickets'
import { Route as PortalTasksRouteImport } from './routes/portal.tasks'
import { Route as PortalServicesRouteImport } from './routes/portal.services'
import { Route as PortalQuotationsRouteImport } from './routes/portal.quotations'
import { Route as PortalProjectsRouteImport } from './routes/portal.projects'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalMeetingsRouteImport } from './routes/portal.meetings'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalKnowledgeRouteImport } from './routes/portal.knowledge'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalHostingRouteImport } from './routes/portal.hosting'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalChangeRequestsRouteImport } from './routes/portal.change-requests'
import { Route as PortalApprovalsRouteImport } from './routes/portal.approvals'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/portal-admin',
  path: '/portal-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InternsRoute = InternsRouteImport.update({
  id: '/interns',
  path: '/interns',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesHistoryRoute = EmployeesHistoryRouteImport.update({
  id: '/employees-history',
  path: '/employees-history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsHistoryRoute = ClientsHistoryRouteImport.update({
  id: '/clients-history',
  path: '/clients-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTicketsRoute = PortalTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTasksRoute = PortalTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => PortalRoute,
} as any)
const PortalServicesRoute = PortalServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuotationsRoute = PortalQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMeetingsRoute = PortalMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalKnowledgeRoute = PortalKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHostingRoute = PortalHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChangeRequestsRoute = PortalChangeRequestsRouteImport.update({
  id: '/change-requests',
  path: '/change-requests',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApprovalsRoute = PortalApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/cases': typeof CasesRoute
  '/catalog': typeof CatalogRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/clients-history': typeof ClientsHistoryRoute
  '/communication': typeof CommunicationRoute
  '/docs': typeof DocsRoute
  '/employees': typeof EmployeesRoute
  '/employees-history': typeof EmployeesHistoryRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/interns': typeof InternsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/it': typeof ItRoute
  '/leaves': typeof LeavesRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal-admin': typeof PortalAdminRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/tax': typeof TaxRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verification': typeof VerificationRoute
  '/portal/approvals': typeof PortalApprovalsRoute
  '/portal/change-requests': typeof PortalChangeRequestsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/hosting': typeof PortalHostingRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/knowledge': typeof PortalKnowledgeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/meetings': typeof PortalMeetingsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/quotations': typeof PortalQuotationsRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/tasks': typeof PortalTasksRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/cases': typeof CasesRoute
  '/catalog': typeof CatalogRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/clients-history': typeof ClientsHistoryRoute
  '/communication': typeof CommunicationRoute
  '/docs': typeof DocsRoute
  '/employees': typeof EmployeesRoute
  '/employees-history': typeof EmployeesHistoryRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/interns': typeof InternsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/it': typeof ItRoute
  '/leaves': typeof LeavesRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/portal-admin': typeof PortalAdminRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/tax': typeof TaxRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verification': typeof VerificationRoute
  '/portal/approvals': typeof PortalApprovalsRoute
  '/portal/change-requests': typeof PortalChangeRequestsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/hosting': typeof PortalHostingRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/knowledge': typeof PortalKnowledgeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/meetings': typeof PortalMeetingsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/quotations': typeof PortalQuotationsRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/tasks': typeof PortalTasksRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/cases': typeof CasesRoute
  '/catalog': typeof CatalogRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/clients-history': typeof ClientsHistoryRoute
  '/communication': typeof CommunicationRoute
  '/docs': typeof DocsRoute
  '/employees': typeof EmployeesRoute
  '/employees-history': typeof EmployeesHistoryRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/interns': typeof InternsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/it': typeof ItRoute
  '/leaves': typeof LeavesRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal-admin': typeof PortalAdminRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/tax': typeof TaxRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/verification': typeof VerificationRoute
  '/portal/approvals': typeof PortalApprovalsRoute
  '/portal/change-requests': typeof PortalChangeRequestsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/hosting': typeof PortalHostingRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/knowledge': typeof PortalKnowledgeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/meetings': typeof PortalMeetingsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/quotations': typeof PortalQuotationsRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/tasks': typeof PortalTasksRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/attendance'
    | '/audit'
    | '/cases'
    | '/catalog'
    | '/certificates'
    | '/clients'
    | '/clients-history'
    | '/communication'
    | '/docs'
    | '/employees'
    | '/employees-history'
    | '/feedback'
    | '/finance'
    | '/hr'
    | '/interns'
    | '/inventory'
    | '/invoices'
    | '/it'
    | '/leaves'
    | '/letters'
    | '/login'
    | '/logs'
    | '/portal'
    | '/portal-admin'
    | '/projects'
    | '/purchase'
    | '/quotations'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/tax'
    | '/transactions'
    | '/users'
    | '/verification'
    | '/portal/approvals'
    | '/portal/change-requests'
    | '/portal/documents'
    | '/portal/hosting'
    | '/portal/invoices'
    | '/portal/knowledge'
    | '/portal/login'
    | '/portal/meetings'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/quotations'
    | '/portal/services'
    | '/portal/tasks'
    | '/portal/tickets'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/attendance'
    | '/audit'
    | '/cases'
    | '/catalog'
    | '/certificates'
    | '/clients'
    | '/clients-history'
    | '/communication'
    | '/docs'
    | '/employees'
    | '/employees-history'
    | '/feedback'
    | '/finance'
    | '/hr'
    | '/interns'
    | '/inventory'
    | '/invoices'
    | '/it'
    | '/leaves'
    | '/letters'
    | '/login'
    | '/logs'
    | '/portal-admin'
    | '/projects'
    | '/purchase'
    | '/quotations'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/tax'
    | '/transactions'
    | '/users'
    | '/verification'
    | '/portal/approvals'
    | '/portal/change-requests'
    | '/portal/documents'
    | '/portal/hosting'
    | '/portal/invoices'
    | '/portal/knowledge'
    | '/portal/login'
    | '/portal/meetings'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/quotations'
    | '/portal/services'
    | '/portal/tasks'
    | '/portal/tickets'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/attendance'
    | '/audit'
    | '/cases'
    | '/catalog'
    | '/certificates'
    | '/clients'
    | '/clients-history'
    | '/communication'
    | '/docs'
    | '/employees'
    | '/employees-history'
    | '/feedback'
    | '/finance'
    | '/hr'
    | '/interns'
    | '/inventory'
    | '/invoices'
    | '/it'
    | '/leaves'
    | '/letters'
    | '/login'
    | '/logs'
    | '/portal'
    | '/portal-admin'
    | '/projects'
    | '/purchase'
    | '/quotations'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/tax'
    | '/transactions'
    | '/users'
    | '/verification'
    | '/portal/approvals'
    | '/portal/change-requests'
    | '/portal/documents'
    | '/portal/hosting'
    | '/portal/invoices'
    | '/portal/knowledge'
    | '/portal/login'
    | '/portal/meetings'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/quotations'
    | '/portal/services'
    | '/portal/tasks'
    | '/portal/tickets'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditRoute: typeof AuditRoute
  CasesRoute: typeof CasesRoute
  CatalogRoute: typeof CatalogRoute
  CertificatesRoute: typeof CertificatesRoute
  ClientsRoute: typeof ClientsRoute
  ClientsHistoryRoute: typeof ClientsHistoryRoute
  CommunicationRoute: typeof CommunicationRoute
  DocsRoute: typeof DocsRoute
  EmployeesRoute: typeof EmployeesRoute
  EmployeesHistoryRoute: typeof EmployeesHistoryRoute
  FeedbackRoute: typeof FeedbackRoute
  FinanceRoute: typeof FinanceRoute
  HrRoute: typeof HrRoute
  InternsRoute: typeof InternsRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  ItRoute: typeof ItRoute
  LeavesRoute: typeof LeavesRoute
  LettersRoute: typeof LettersRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  PortalRoute: typeof PortalRouteWithChildren
  PortalAdminRoute: typeof PortalAdminRoute
  ProjectsRoute: typeof ProjectsRoute
  PurchaseRoute: typeof PurchaseRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TasksRoute: typeof TasksRoute
  TaxRoute: typeof TaxRoute
  TransactionsRoute: typeof TransactionsRoute
  UsersRoute: typeof UsersRoute
  VerificationRoute: typeof VerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-admin': {
      id: '/portal-admin'
      path: '/portal-admin'
      fullPath: '/portal-admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interns': {
      id: '/interns'
      path: '/interns'
      fullPath: '/interns'
      preLoaderRoute: typeof InternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees-history': {
      id: '/employees-history'
      path: '/employees-history'
      fullPath: '/employees-history'
      preLoaderRoute: typeof EmployeesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients-history': {
      id: '/clients-history'
      path: '/clients-history'
      fullPath: '/clients-history'
      preLoaderRoute: typeof ClientsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tickets': {
      id: '/portal/tickets'
      path: '/tickets'
      fullPath: '/portal/tickets'
      preLoaderRoute: typeof PortalTicketsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tasks': {
      id: '/portal/tasks'
      path: '/tasks'
      fullPath: '/portal/tasks'
      preLoaderRoute: typeof PortalTasksRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/services': {
      id: '/portal/services'
      path: '/services'
      fullPath: '/portal/services'
      preLoaderRoute: typeof PortalServicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/quotations': {
      id: '/portal/quotations'
      path: '/quotations'
      fullPath: '/portal/quotations'
      preLoaderRoute: typeof PortalQuotationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/meetings': {
      id: '/portal/meetings'
      path: '/meetings'
      fullPath: '/portal/meetings'
      preLoaderRoute: typeof PortalMeetingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/knowledge': {
      id: '/portal/knowledge'
      path: '/knowledge'
      fullPath: '/portal/knowledge'
      preLoaderRoute: typeof PortalKnowledgeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/hosting': {
      id: '/portal/hosting'
      path: '/hosting'
      fullPath: '/portal/hosting'
      preLoaderRoute: typeof PortalHostingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/change-requests': {
      id: '/portal/change-requests'
      path: '/change-requests'
      fullPath: '/portal/change-requests'
      preLoaderRoute: typeof PortalChangeRequestsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/approvals': {
      id: '/portal/approvals'
      path: '/approvals'
      fullPath: '/portal/approvals'
      preLoaderRoute: typeof PortalApprovalsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalApprovalsRoute: typeof PortalApprovalsRoute
  PortalChangeRequestsRoute: typeof PortalChangeRequestsRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalHostingRoute: typeof PortalHostingRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalKnowledgeRoute: typeof PortalKnowledgeRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMeetingsRoute: typeof PortalMeetingsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalProjectsRoute: typeof PortalProjectsRoute
  PortalQuotationsRoute: typeof PortalQuotationsRoute
  PortalServicesRoute: typeof PortalServicesRoute
  PortalTasksRoute: typeof PortalTasksRoute
  PortalTicketsRoute: typeof PortalTicketsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApprovalsRoute: PortalApprovalsRoute,
  PortalChangeRequestsRoute: PortalChangeRequestsRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalHostingRoute: PortalHostingRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalKnowledgeRoute: PortalKnowledgeRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMeetingsRoute: PortalMeetingsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalProjectsRoute: PortalProjectsRoute,
  PortalQuotationsRoute: PortalQuotationsRoute,
  PortalServicesRoute: PortalServicesRoute,
  PortalTasksRoute: PortalTasksRoute,
  PortalTicketsRoute: PortalTicketsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AttendanceRoute: AttendanceRoute,
  AuditRoute: AuditRoute,
  CasesRoute: CasesRoute,
  CatalogRoute: CatalogRoute,
  CertificatesRoute: CertificatesRoute,
  ClientsRoute: ClientsRoute,
  ClientsHistoryRoute: ClientsHistoryRoute,
  CommunicationRoute: CommunicationRoute,
  DocsRoute: DocsRoute,
  EmployeesRoute: EmployeesRoute,
  EmployeesHistoryRoute: EmployeesHistoryRoute,
  FeedbackRoute: FeedbackRoute,
  FinanceRoute: FinanceRoute,
  HrRoute: HrRoute,
  InternsRoute: InternsRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  ItRoute: ItRoute,
  LeavesRoute: LeavesRoute,
  LettersRoute: LettersRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  PortalRoute: PortalRouteWithChildren,
  PortalAdminRoute: PortalAdminRoute,
  ProjectsRoute: ProjectsRoute,
  PurchaseRoute: PurchaseRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TasksRoute: TasksRoute,
  TaxRoute: TaxRoute,
  TransactionsRoute: TransactionsRoute,
  UsersRoute: UsersRoute,
  VerificationRoute: VerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
